<center> 

# DSSI: Summer 2025
    
## PyTorch Tutorial

#### This notebook has been adopted from the PyTorch Tutorial authored by Dilara Soylu and Ethan Chi for the Stanford CS224N course<center>


<center>
<img src="https://raw.githubusercontent.com/amandakube/Data118LectureImages/main/UChicago_DSI.png" alt="UC-DSI" width="300" height="100">
</center>


In this notebook, we will have a basic introduction to `PyTorch` and work on a toy NLP task. Following resources were also used in preparation of this notebook:
* ["Word Window Classification" tutorial notebook]((https://web.stanford.edu/class/archive/cs/cs224n/cs224n.1204/materials/ww_classifier.ipynb) by Matt Lamm, from Winter 2020 offering of CS224N
* Official PyTorch Documentation on [Deep Learning with PyTorch: A 60 Minute Blitz](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) by Soumith Chintala

## Introduction
[PyTorch](https://pytorch.org/) is a deep learning framework, one of the two main frameworks alongside [TensorFlow](https://www.tensorflow.org/). The installation can be done via Pip or Conda, as described [here](https://pytorch.org/). Let's start by importing PyTorch:

In [ ]:
import torch
import torch.nn as nn

# Import pprint, module we use for making our print statements prettier
import pprint
pp = pprint.PrettyPrinter()

We are all set to start our tutorial. Let's dive in!

##Part 1: Tensors

**Tensors** are PyTorch's most basic building block. Each tensor is a block of multi-dimensional matrix.

For example, a 256x256 square image in the rbg scale might be represented by a `3x256x256` tensor, where the first dimension represents color.

In other contexts of deep learning, the first dimension of an n-d tensor represents batch size.


### **Initializing Tensors**

Let's see how to create tensors and understand their shapes:

In [ ]:
list_of_lists = [
  [1, 2, 3],
  [4, 5, 6],
]
print(list_of_lists)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
data = torch.tensor(list_of_lists)
print(data)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Initializing a tensor
data = torch.tensor([
                     [0, 1],
                     [2, 3],
                     [4, 5]
                    ])
print(data)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [ ]:
input = torch.ones(2,3,2)
print(input,'\n')
x= input[0]
print(x)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]) 

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


#### **Question:**

Can you illustrate the shape of the `input` tensor?
```python
input = torch.ones(2,3,1,2)
```

### **Data Type**:
Each tensor has a **data type**: the major data types you'll need to worry about are floats (`torch.float32`) and integers (`torch.int`). You can specify the data type explicitly when you create the tensor:

In [ ]:
# Initializing a tensor with an explicit data type
# Notice the dots after the numbers, which specify that they're floats
data = torch.tensor([
                     [0, 1],
                     [2, 3],
                     [4, 5]
                    ], dtype=torch.float32)
print(data)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])


In [ ]:
# Initializing a tensor with an explicit data type
# Notice the dots after the numbers, which specify that they're floats
data = torch.tensor([
                     [0.11111111, 1],
                     [2, 3],
                     [4, 5]
                    ], dtype=torch.float32)
print(data)

tensor([[0.1111, 1.0000],
        [2.0000, 3.0000],
        [4.0000, 5.0000]])


Utility functions also exist to create tensors with given shapes and contents:

In [ ]:
zeros = torch.zeros(2, 5)  # a tensor of all zeros
print(zeros)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
ones = torch.ones(3, 4)   # a tensor of all ones
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
rr = torch.arange(1, 10) # range from [1, 10)
print(rr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
rr + 2

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
rr * 2

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a = torch.tensor([[1, 2], [2, 3], [4, 5]])      # (3, 2)
b = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])  # (2, 4)

print("A is", a)
print("B is", b)
print("The product is", a.matmul(b)) #(3, 4)
print("The other product is", a @ b) # +, -, *, @

A is tensor([[1, 2],
        [2, 3],
        [4, 5]])
B is tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
The product is tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])
The other product is tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])


The **shape** of a matrix (which can be accessed by `.shape`) is defined as the dimensions of the matrix. Here's some examples:

In [ ]:
matr_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matr_2d.shape)
print(matr_2d)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
matr_3d = torch.tensor([[[1, 2, 3, 4], [-2, 5, 6, 9]], [[5, 6, 7, 2], [8, 9, 10, 4]], [[-3, 2, 2, 1], [4, 6, 5, 9]]])
print(matr_3d)
print(matr_3d.shape)

tensor([[[ 1,  2,  3,  4],
         [-2,  5,  6,  9]],

        [[ 5,  6,  7,  2],
         [ 8,  9, 10,  4]],

        [[-3,  2,  2,  1],
         [ 4,  6,  5,  9]]])
torch.Size([3, 2, 4])


### **Reshaping**:  
Reshaping functions help to alter the structural organization of your tensors. The number of parameters you send to the reshape function depends upon the desired shape of your tensor. Reshaping tensors can make batch operations easier (more on that later), but be careful that the data is reshaped in the order you expect:

In [ ]:
rr = torch.arange(1, 16)
print("The shape is currently", rr.shape)
print("The contents are currently", rr)
print()
rr = rr.view(5, 3)
print("After reshaping, the shape is currently", rr.shape)
print("The contents are currently", rr)
print()

rr = rr.reshape(1, 3, 5)
print("After reshaping, the shape is currently", rr.shape)
print("The contents are currently", rr)

The shape is currently torch.Size([15])
The contents are currently tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

After reshaping, the shape is currently torch.Size([5, 3])
The contents are currently tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])

After reshaping, the shape is currently torch.Size([1, 3, 5])
The contents are currently tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]]])


A single dimension among the parameters to your `.reshape` function may be -1 , in which case it’s inferred from the remaining dimensions and the number of elements in input.

In [ ]:
rr = torch.arange(1,13)
print("The initial shape is", rr.shape,'\n')

rr = rr.reshape(2, -1, 3)
print("After reshaping, the shape is currently", rr.shape)
print("The contents are currently", rr,'\n')

rr = rr.reshape(-1)
print("After reshaping, the shape is currently", rr.shape)
print("The contents are currently", rr,'\n')

The shape is currently torch.Size([12]) 

After reshaping, the shape is currently torch.Size([2, 2, 3])
The contents are currently tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]) 

After reshaping, the shape is currently torch.Size([12])
The contents are currently tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]) 



####Some other functions to alter tensor shapes:

`torch.squeeze()` returns a tensor with all specified dimensions of input of size 1 removed. We can also collapse specific dimensions by passing them as arguments.

In [ ]:
input = torch.ones(2,3,1,2)
x= input.squeeze()
print(x,'\n')

x= input.squeeze(2)
print(x,'\n')

x= input.squeeze(1)
print(x,'\n')

In [ ]:
input = torch.tensor([[[1],[2],[3],[4]],[[1],[2],[3],[4]]])
x= input.squeeze(1)
print(x,'\n')

x= input.squeeze(2)
print(x,'\n')

`torch.unsqueeze()` is the opposite of the `squeeze` operation. It adds an extra dimension within the tensor at the specified dimension that is passed as a parameter to the function.
The parameter `dim` can have a value within the range $[-input.dim() - 1, input.dim() + 1)$.

In [ ]:
input = torch.tensor([[1, 2, 3, 4],[5, 6, 7, 8]])
print('Current tensor shape:',input.shape,'\n')

y= torch.unsqueeze(input, 0)
print('tensor shape upon unsqueeze operation:',y.shape)
print(y,'\n')

y= torch.unsqueeze(input, 1)
print('tensor shape upon unsqueeze operation:',y.shape)
print(y,'\n')

y= torch.unsqueeze(input, 2)
print('tensor shape upon unsqueeze operation:',y.shape)
print(y,'\n')

#### **Exercise**: Initialize a tensor of shape (5,3,2) with values ranging from 21 to 50. Hint: You should use the `reshape` function

<details>

<summary>Solution</summary>

```python
x = torch.arange(21,51)
x = x.view(5,3,2)
print("Current tensor is:", x)
```

</details>

### **Integration with Numpy**:
Finally, you can also inter-convert tensors with **NumPy arrays**:

In [ ]:
import numpy as np

# numpy.ndarray --> torch.Tensor:
arr = np.array([[1, 0, 5]])
data = torch.tensor(arr)
print("This is a torch.tensor", data)

# torch.Tensor --> numpy.ndarray:
new_arr = data.numpy()
print("This is a np.ndarray", new_arr)

This is a torch.tensor tensor([[1, 0, 5]])
This is a np.ndarray [[1 0 5]]


### **Vectorized Operations**:
One of the reasons why we use **tensors** is ***vectorized operations***: operations that be conducted in parallel over a particular dimension of a tensor.

![An image](https://miro.medium.com/v2/format:webp/1*_D5ZvufDS38WkhK9rK32hQ.jpeg)

In [ ]:
data = torch.arange(1, 36, dtype=torch.float32).reshape(5, 7)
print("Data is:", data)

# We can perform operations like *sum* over each row...
print("Taking the sum over rows:")
print(data.sum(dim=1)) #(5,)

# or over each column.
print("Taking thep sum over columns:")
print(data.sum(dim=0)) #(7,)

# Other operations are available:
print("Taking the stdev over rows:")
print(data.std(dim=1))


Data is: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19., 20., 21.],
        [22., 23., 24., 25., 26., 27., 28.],
        [29., 30., 31., 32., 33., 34., 35.]])
Taking the sum over rows:
tensor([ 28.,  77., 126., 175., 224.])
Taking thep sum over columns:
tensor([ 75.,  80.,  85.,  90.,  95., 100., 105.])
Taking the stdev over rows:
tensor([2.1602, 2.1602, 2.1602, 2.1602, 2.1602])


In [ ]:
data = torch.arange(1, 19, dtype=torch.float32).reshape(3, 2, 3)
print("Data is:",data)
print()

print(data.sum(dim=0))
print(data.sum(dim=0).shape)

Data is: tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[13., 14., 15.],
         [16., 17., 18.]]])

tensor([[21., 24., 27.],
        [30., 33., 36.]])
torch.Size([2, 3])


In [ ]:
data = torch.arange(1, 7, dtype=torch.float32).reshape(1, 2, 3)
print("Data is:",data)
print()

print(data.sum(dim=0))
print(data.sum(dim=0).shape)
print()

print(data.sum(dim=0).sum(dim=0))
print(data.sum(dim=0).sum(dim=0).shape)

Data is: tensor([[[1., 2., 3.],
         [4., 5., 6.]]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])

tensor([5., 7., 9.])
torch.Size([3])


In [ ]:
data.sum()

tensor(15.9000)

#### **Question**: What is the difference between the sum operations in the following two code snippets for the previous tensor in question?
```python
print(data.sum(dim=0))
print(data.sum(dim=0).sum(dim=0))
```

#### **Exercise:**

Write code that creates a `torch.tensor` initialized with floating point values having the following contents:
$\begin{bmatrix} 1 & 2.2 & 9.6 \\ 4 & -7.2 & 6.3 \end{bmatrix}$

Now compute the average of each row (`.mean()`) and each column.

What's the shape of the results?



<details>

<summary>Solution</summary>

```python
data = torch.tensor([[1, 2.2, 9.6],
                     [4, -7.2, 6.3]], dtype=torch.float32)
print('Data is: ', data)
print()

print('Mean of each row is: ', data.mean(dim=1))
print('Shape is: ', data.mean(dim=1).shape)
print()

print('Mean of each column is: ', data.mean(dim=0))
print('Shape is: ', data.mean(dim=0).shape)
print()
```

</details>

### **Indexing**

You can access arbitrary elements of a tensor using the `[]` operator.

In [ ]:
# Initialize an example tensor
x = torch.Tensor([
                  [[1, 2], [3, 4]],
                  [[5, 6], [7, 8]],
                  [[9, 10], [11, 12]]
                 ])
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [ ]:
x.shape

torch.Size([3, 2, 2])

Access the 0th element, which is the first row. Equivalent to ` x[0, :]`

In [ ]:
x[0]

tensor([[1., 2.],
        [3., 4.]])

Print the first elements along dimension 0

In [ ]:
x[:, 0]

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

We can also index into multiple dimensions with `:`.

In [ ]:
# Get the top left element of each element in our tensor
x[:, 0, 0]

tensor([1., 5., 9.])

In [ ]:
x[:, :, :]

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

We can also access arbitrary elements in each dimension.

In [ ]:
# Let's access the 0th and 1st elements, each twice
# same as stacking x[0], x[0], x[1], x[1]
i = torch.tensor([0, 0, 1, 1])
x[i]

tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[5., 6.],
         [7., 8.]]])

In [ ]:
# Let's access the 0th elements of the 1st and 2nd elements

i = torch.tensor([1, 2])
j = torch.tensor([0])
x[i, j]

tensor([[ 5.,  6.],
        [ 9., 10.]])

Notice the difference with `x[[1,2][0]]`

In [ ]:
x[[1,2][0]]

tensor([[5., 6.],
        [7., 8.]])

We can get a `Python` scalar value from a tensor with `item()`.

In [ ]:
x[0, 0, 0]

tensor(1.)

In [ ]:
x[0, 0, 0].item()

1.0

#### **Exercise**:

Write code that creates a `torch.tensor` with the following contents:
$\begin{bmatrix} 1 & 2.2 & 9.6 \\ 4 & -7.2 & 6.3 \end{bmatrix}$

How do you get the first column? The first row?



<details>

<summary>Solution</summary>

```python
data = torch.tensor([[1, 2.2, 9.6],
                     [4, -7.2, 6.3]], dtype=torch.float32)
print('Data is: ', data)
print()

print('First row is: ', data[0])
print()

print('First column is: ', data[:,0])
print()
```

</details>

##Part 2:  Autograd
Pytorch is well-known for its automatic differentiation feature. We can call the `backward()` method to ask `PyTorch` to calculate the gradients, which are then stored in the `grad` attribute.

In [ ]:
# Create an example tensor
# requires_grad parameter tells PyTorch to store gradients
x = torch.tensor([2.], requires_grad=True)

# Print the gradient if it is calculated
# Currently None since x is a scalar
pp.pprint(x.grad)

None


Calculating the gradient of y with respect to x, where
$y=3x^{2}$ is:

$\frac{dy}{dx} = 6x$

In [ ]:
y = x * x * 3 # 3x^2
y.backward()
pp.pprint(x.grad)

tensor([12.])


Let's run backprop from a different tensor again to see what happens.

In [ ]:
z = x * x * 3 # 3x^2
z.backward()
pp.pprint(x.grad)

tensor([24.])


In [ ]:
x.grad = None
z = x * x * 3 # 3x^2
z.backward()
# y = x * x * 3
pp.pprint(x.grad)

tensor([12.])


In [ ]:
z = x * x * 3 # 3x^2
z.backward()
# y = x * x * 3
pp.pprint(x.grad)

tensor([24.])


In [ ]:
z = x * x * 3 # 3x^2
z.backward()
# y = x * x * 3
pp.pprint(x.grad)

tensor([36.])


We can see that the `x.grad` is updated to be the sum of the gradients calculated so far. When we run backprop in a neural network, we sum up all the gradients for a particular neuron before making an update. This is exactly what is happening here! This is also the reason why we need to run `zero_grad()` in every training iteration (more on this later). Otherwise our gradients would keep building up from one training iteration to the other, which would cause our updates to be wrong.

## Customized Backward Function
In some rare cases, you might want to design your own operators, or calculate higher order gradients that are not supported by Pytorch. In these cases you can define your own function with customized forward & backward computation. However, keep in mind that always check if something is already implemented by Pytorch (which is very likely) before customizing your own forward & backward computation. See more at https://pytorch.org/docs/stable/notes/extending.html.

## Part 3: Neural Network Module

So far we have looked into the tensors, their properties and basic operations on tensors. These are especially useful to get familiar with if we are building the layers of our network from scratch. But moving forward, we will mostly be using predefined blocks in the `torch.nn` module of `PyTorch` or others. We will then put together these blocks to create complex networks. Let's start by importing this module with an alias so that we don't have to type `torch` every time we use it.

In [ ]:
import torch.nn as nn

### **Linear Layer**
We can use `nn.Linear(H_in, H_out)` to create a a linear layer. This will take a matrix of `(N, *, H_in)` dimensions and output a matrix of `(N, *, H_out)`. The `*` denotes that there could be arbitrary number of dimensions in between.

Typically dimension 0 in the input reptesents the number of mini-batches and dimension 1 represents th batch size, i.e. number of records in each mini-batch. Here we can interpret the input tensor to have two mini-batches each with 3 records of input vectors each of size 4.

The linear layer performs the operation $xA^{T}+b$, where weight `A` and bias `b` are initialized randomly.

Shape of A : `(H_out, H_in)` Shape of b : `(H_out)`

If we don't want the linear layer to learn the bias parameters, we can initialize our layer with `bias=False`.

In [ ]:
# Create the inputs
input = torch.ones(1,3,4)
# N* H_in -> N*H_out


# Make a linear layers transforming N,*,H_in dimensinal inputs to N,*,H_out
# dimensional outputs
linear = nn.Linear(4, 2)
linear_output = linear(input)
linear_output

tensor([[[-0.6933, -1.2225],
         [-0.6933, -1.2225],
         [-0.6933, -1.2225]]], grad_fn=<ViewBackward0>)

In [ ]:
linear_output.shape

torch.Size([1, 3, 2])

In [ ]:
list(linear.named_parameters()) # A and b

[('weight',
  Parameter containing:
  tensor([[-0.4129,  0.3116, -0.4367, -0.4965],
          [-0.4764,  0.4366, -0.2696, -0.4289]], requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([ 0.3413, -0.4843], requires_grad=True))]

In [ ]:
# Data of shape [batch_size, feature_dim] # 4
# [batch_size, output_dim] # 2

# weight shape: (2,4) bias: (2,1)

### **Other Module Layers**
There are several other preconfigured layers in the `nn` module. Some commonly used examples are `nn.Conv2d`, `nn.ConvTranspose2d`, `nn.BatchNorm1d`, `nn.BatchNorm2d`, `nn.Upsample` and `nn.MaxPool2d` among many others. We will learn more about these as we progress in the course. For now, the only important thing to remember is that we can treat each of these layers as plug and play components: we will be providing the required dimensions and `PyTorch` will take care of setting them up.

### **Activation Function Layer**
We can also use the `nn` module to apply activations functions to our tensors. Activation functions are used to add non-linearity to our network. Some examples of activations functions are `nn.ReLU()`, `nn.Sigmoid()` and `nn.LeakyReLU()`. Activation functions operate on each element seperately, so the shape of the tensors we get as an output are the same as the ones we pass in.

In [ ]:
linear_output

tensor([[[-0.6933, -1.2225],
         [-0.6933, -1.2225],
         [-0.6933, -1.2225]]], grad_fn=<ViewBackward0>)

In [ ]:
sigmoid = nn.Sigmoid()
output = sigmoid(linear_output)
output

tensor([[[0.3333, 0.2275],
         [0.3333, 0.2275],
         [0.3333, 0.2275]]], grad_fn=<SigmoidBackward0>)

### **Putting the Layers Together**
So far we have seen that we can create layers and pass the output of one as the input of the next. Instead of creating intermediate tensors and passing them around, we can use `nn.Sequentual`, which does exactly that.

In [ ]:
model = nn.Sequential(
    nn.Linear(4, 2),
    nn.Sigmoid()
)

input = torch.ones(2,3,4)
output = model(input)
output

tensor([[[0.5489, 0.3664],
         [0.5489, 0.3664],
         [0.5489, 0.3664]],

        [[0.5489, 0.3664],
         [0.5489, 0.3664],
         [0.5489, 0.3664]]], grad_fn=<SigmoidBackward0>)

### **Configure your own Neural Network**

Instead of using the predefined modules, we can also build our own by extending the `nn.Module` class. For example, we can build a the `nn.Linear` (which also extends `nn.Module`) on our own using the tensor introduced earlier! We can also build new, more complex modules, such as a custom neural network. You will be practicing these in the later assignment.

To create a custom module, the first thing we have to do is to extend the `nn.Module`. We can then initialize our parameters in the `__init__` function, starting with a call to the `__init__` function of the super class. All the class attributes we define which are `nn` module objects are treated as parameters, which can be learned during the training. Tensors are not parameters, but they can be turned into parameters if they are wrapped in `nn.Parameter` class.

All classes extending `nn.Module` are also expected to implement a `forward(x)` function, where `x` is a tensor. This is the function that is called when a parameter is passed to our module, such as in `model(x)`.

In [ ]:
class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    # Call to the __init__ function of the super class
    super(MultilayerPerceptron, self).__init__()

    # Bookkeeping: Saving the initialization parameters
    self.input_size = input_size
    self.hidden_size = hidden_size

    # Defining of our model
    # There isn't anything specific about the naming of `self.model`. It could
    # be something arbitrary.
    self.model = nn.Sequential(
        nn.Linear(self.input_size, self.hidden_size),
        nn.ReLU(),
        nn.Linear(self.hidden_size, self.input_size),
        nn.Sigmoid()
    )

  def forward(self, x):
    output = self.model(x)
    return output

Here is an alternative way to define the same class. You can see that we can replace `nn.Sequential` by defining the individual layers in the `__init__` method and connecting the in the `forward` method.

In [ ]:
class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    # Call to the __init__ function of the super class
    super(MultilayerPerceptron, self).__init__()

    # Bookkeeping: Saving the initialization parameters
    self.input_size = input_size
    self.hidden_size = hidden_size

    # Defining of our layers
    self.linear = nn.Linear(self.input_size, self.hidden_size)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(self.hidden_size, self.input_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    linear = self.linear(x)
    relu = self.relu(linear)
    linear2 = self.linear2(relu)
    output = self.sigmoid(linear2)
    return output

Now that we have defined our class, we can instantiate it and see what it does.

In [ ]:
# Make a sample input
input = torch.randn(2, 5)

# Create our model
model = MultilayerPerceptron(5, 3)

# Pass our input through our model
model(input)

tensor([[0.5654, 0.5655, 0.5070, 0.5127, 0.5522],
        [0.5119, 0.5654, 0.4424, 0.5344, 0.5221]], grad_fn=<SigmoidBackward0>)

We can inspect the parameters of our model with `named_parameters()` and `parameters()` methods.

In [ ]:
list(model.named_parameters())

[('linear.weight',
  Parameter containing:
  tensor([[-0.3340,  0.4383, -0.0491,  0.0756,  0.0794],
          [-0.2252,  0.1520,  0.3585, -0.2508,  0.2671],
          [ 0.1614,  0.3414,  0.1201, -0.1165, -0.0461]], requires_grad=True)),
 ('linear.bias',
  Parameter containing:
  tensor([0.1645, 0.0539, 0.3023], requires_grad=True)),
 ('linear2.weight',
  Parameter containing:
  tensor([[-0.2881, -0.4134,  0.4523],
          [-0.3711, -0.2440, -0.1232],
          [-0.1544,  0.0572,  0.5610],
          [-0.2668,  0.2633, -0.3468],
          [-0.4435,  0.3372,  0.0793]], requires_grad=True)),
 ('linear2.bias',
  Parameter containing:
  tensor([ 0.1302,  0.3762, -0.2595,  0.1645,  0.0984], requires_grad=True))]

##Part 4: Optimization
We have showed how gradients are calculated with the `backward()` function. Having the gradients isn't enought for our models to learn. We also need to know how to update the parameters of our models. This is where the optomozers comes in. `torch.optim` module contains several optimizers that we can use. Some popular examples are `optim.SGD` and `optim.Adam`. When initializing optimizers, we pass our model parameters, which can be accessed with `model.parameters()`, telling the optimizers which values it will be optimizing. Optimizers also has a learning rate (`lr`) parameter, which determines how big of an update will be made in every step. Different optimizers have different hyperparameters as well.

In [ ]:
import torch.optim as optim

After we have our optimization function, we can define a `loss` that we want to optimize for. We can either define the loss ourselves, or use one of the predefined loss function in `PyTorch`, such as `nn.BCELoss()`.

Let's put everything together now! We will start by creating some dummy data.

In [ ]:
# Create the training data
train_y = torch.ones(10, 5)

# Add some noise to our goal y to generate our x
# We want out model to predict our original data, albeit the noise
train_x = train_y + torch.randn_like(train_y)
train_x

tensor([[-0.8610, -0.0386,  2.6457,  1.3627,  1.9769],
        [ 1.6039,  0.7143,  1.2866,  1.1706,  1.3975],
        [ 1.3279, -0.1397,  1.4089, -0.6504,  0.8368],
        [ 1.1497, -0.3449,  0.2480, -0.3123,  0.3468],
        [ 0.3632,  1.6973,  1.7188,  0.1876,  1.8549],
        [-0.5901, -0.5459,  0.1903,  0.9606,  1.4824],
        [ 0.2270,  0.8169,  0.7199,  2.5478, -0.8477],
        [ 0.1177,  0.2179,  1.1681,  1.7908, -0.4242],
        [ 2.0764, -1.2936,  1.8937,  0.6838,  2.5949],
        [ 0.9513,  1.7441,  1.9951,  0.5010,  1.1311]])

In [ ]:
# Create validation data to check how our model performs on it
val_y = torch.ones(10, 5)
val_x = val_y + torch.randn_like(val_y)

Now, we can define our model, optimizer and the loss function.

In [ ]:
#set seed and device
torch.manual_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Instantiate the model
model = MultilayerPerceptron(5, 3)

# Define the optimizer
learning_rate = 1e-1
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Define loss using a predefined loss function
loss = nn.MSELoss()

#number of epochs
num_epochs = 100

best_val_loss = float("inf")

# Lets initialize our model with random weight and see how it is doing
y_pred = model(train_x)
loss(y_pred, train_y).item()

0.2762928009033203

Let's see if we can have our model achieve a smaller loss. Now that we have everything we need, we can setup our training loop.

In [ ]:
for epoch in range(num_epochs):
  #Training
  model.train()

  # Set the gradients to 0
  optimizer.zero_grad()

  # Get the model predictions
  input = train_x.to(device)
  y_pred = model(input)

  # Get the loss
  training_loss = loss(y_pred, train_y)

  # Print stats
  print(f"Epoch {epoch}: training loss: {training_loss}")

  # Compute the gradients
  training_loss.backward()

  # Take a step to optimize the weights
  optimizer.step()

  #============end of an epoch============

  #End of Training; validation at the end of every epocj

  model.eval() #important to call because we dont want to collect gradients

  with torch.no_grad():
    # Get the model predictions
    input = val_x.to(device)
    y_pred = model(input)

    val_loss = loss(y_pred, val_y)
    print(f"Validation loss: {val_loss}")

    if(val_loss<best_val_loss):
      best_val_loss = val_loss
      print("Saving model checkpoint!")
  print("============")

In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3648, -0.2708, -0.7760, -0.1016, -0.9091],
         [-0.1792,  0.6089,  0.1631,  0.8415, -1.4136],
         [ 1.2489,  0.7165,  1.3374,  1.1227,  1.2665]], requires_grad=True),
 Parameter containing:
 tensor([-0.6869,  0.3669,  1.2609], requires_grad=True),
 Parameter containing:
 tensor([[0.5213, 1.1576, 1.3125],
         [0.7837, 0.8902, 1.7669],
         [0.3491, 0.7572, 1.2263],
         [0.4548, 1.1026, 1.2797],
         [1.3996, 0.6321, 1.7409]], requires_grad=True),
 Parameter containing:
 tensor([1.8080, 1.4370, 1.9781, 1.9259, 2.0277], requires_grad=True)]

You can see that our loss is decreasing. Let's check the predictions of our model now and see if they are close to our original `y`, which was all `1s`.

In [ ]:
# See how our model performs on the training data
y_pred = model(train_x)
y_pred

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.9998, 1.0000, 0.9997, 0.9998, 1.0000],
        [0.9962, 0.9985, 0.9959, 0.9963, 0.9991],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.9980, 0.9994, 0.9977, 0.9980, 0.9996],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 0.9999, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]], grad_fn=<SigmoidBackward0>)

In [ ]:
# Check how our model performs on new test data
test_y = torch.ones(10, 5)
test_x = test_y + torch.randn_like(test_y)
y_pred = model(test_x)
y_pred

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 0.9999, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [0.9973, 0.9987, 0.9966, 0.9973, 0.9992],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]], grad_fn=<SigmoidBackward0>)

Great! Looks like our model almost perfectly learned to filter out the noise from the `x` that we passed in!

## Part 5: Exercise


As shown in this notebook, train a neural network to make predictions on the following data. Note that we are predicting binary class labels $y ϵ (0,1)$ which is why we use ``torch.nn.BCELoss`` as the loss function which expects your output to be probabilities, that is with the sigmoid activation which we had learnt for Logistic Regression for binary classification.

Creating some training and validation data

In [ ]:
temp = torch.cat((torch.ones(10),torch.zeros(10)),0)
train_y = temp[torch.randperm(temp.size()[0])]
train_x = torch.rand(20,5)
print(train_x)
print(train_y)

tensor([[0.9569, 0.9864, 0.6496, 0.6721, 0.6151],
        [0.5078, 0.4636, 0.5069, 0.6867, 0.9649],
        [0.3704, 0.2886, 0.3789, 0.2584, 0.5850],
        [0.8732, 0.8910, 0.7296, 0.1320, 0.2316],
        [0.3901, 0.4078, 0.5411, 0.0410, 0.6556],
        [0.1186, 0.1836, 0.0843, 0.9357, 0.0265],
        [0.8772, 0.4832, 0.4419, 0.8127, 0.4538],
        [0.8136, 0.8615, 0.0659, 0.6924, 0.5944],
        [0.6075, 0.5730, 0.6368, 0.2595, 0.4360],
        [0.9751, 0.8359, 0.4812, 0.0297, 0.5219],
        [0.1595, 0.9066, 0.1965, 0.4639, 0.3890],
        [0.5890, 0.9705, 0.5475, 0.7896, 0.8881],
        [0.9037, 0.3273, 0.3882, 0.7410, 0.3636],
        [0.7341, 0.3908, 0.1609, 0.7035, 0.5767],
        [0.7229, 0.9967, 0.8414, 0.9740, 0.5268],
        [0.0699, 0.1492, 0.1894, 0.0594, 0.2494],
        [0.0397, 0.0387, 0.2012, 0.0071, 0.1931],
        [0.6907, 0.9170, 0.3513, 0.3546, 0.7670],
        [0.2533, 0.2636, 0.8081, 0.0643, 0.5611],
        [0.9417, 0.5857, 0.6360, 0.2088, 0.4931]])

In [ ]:
temp = torch.cat((torch.ones(8),torch.zeros(7)),0)
val_y = temp[torch.randperm(temp.size()[0])]
val_x = torch.rand(15,5)
print(val_x)
print(val_y)

tensor([[0.0268, 0.3066, 0.4026, 0.0751, 0.1821],
        [0.4184, 0.8794, 0.9828, 0.8181, 0.2014],
        [0.1729, 0.9363, 0.6769, 0.5133, 0.5677],
        [0.0982, 0.3331, 0.9813, 0.3767, 0.4749],
        [0.0848, 0.2203, 0.4898, 0.1894, 0.4380],
        [0.7035, 0.0109, 0.6485, 0.1694, 0.2560],
        [0.6920, 0.8976, 0.3633, 0.2947, 0.0479],
        [0.2422, 0.0622, 0.3856, 0.6020, 0.0316],
        [0.9366, 0.8137, 0.0105, 0.2612, 0.6631],
        [0.3973, 0.4455, 0.2742, 0.9016, 0.2205],
        [0.9146, 0.5323, 0.6005, 0.8901, 0.4176],
        [0.2153, 0.4191, 0.9055, 0.1290, 0.6135],
        [0.0086, 0.7622, 0.6847, 0.5212, 0.7146],
        [0.5006, 0.7767, 0.1042, 0.4266, 0.7218],
        [0.9979, 0.7547, 0.1364, 0.8845, 0.3885]])
tensor([1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0.])


In [ ]:
#create your model


In [ ]:
#initialize your model and training hyperparameters


In [ ]:
# write your training and validation loop


In [ ]:
from sklearn.metrics import accuracy_score

#evaluate model and get accuracy



<details>

<summary>Solution</summary>

```python
class FFNN(nn.Module):

  def __init__(self, input_size, hidden_size):
    # Call to the __init__ function of the super class
    super(FFNN, self).__init__()

    # Bookkeeping: Saving the initialization parameters
    self.input_size = input_size
    self.hidden_size = hidden_size
    self.output_size = 1 #we only want to output probabilities

    # Defining of our layers
    self.linear1 = nn.Linear(self.input_size, self.hidden_size)
    self.relu1 = nn.ReLU()
    self.linear2 = nn.Linear(self.hidden_size, self.hidden_size)
    self.relu2 = nn.ReLU()
    self.linear3 = nn.Linear(self.hidden_size, self.output_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    linear1 = self.linear1(x)
    relu1 = self.relu1(linear1)
    linear2 = self.linear2(relu1)
    relu2 = self.relu2(linear2)
    linear3 = self.linear3(relu2)
    output = self.sigmoid(linear3)
    return output

#set seed and device
torch.manual_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Instantiate the model
model = FFNN(5, 3)

# Define the optimizer
learning_rate = 0.05
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Define loss using a predefined loss function
loss = nn.BCELoss()

#number of epochs
num_epochs = 100

best_val_loss = float("inf")

# Lets initialize our model with random weight and see how it is doing
y_pred = model(train_x)
print(y_pred.squeeze().shape,train_y.shape)
print(loss(y_pred.squeeze(), train_y).item())

for epoch in range(num_epochs):
  #Training
  model.train()

  # Set the gradients to 0
  optimizer.zero_grad()

  # Get the model predictions
  input = train_x.to(device)
  y_pred = model(input)

  # Get the loss
  training_loss = loss(y_pred.squeeze(), train_y)

  # Print stats
  print(f"Epoch {epoch}: training loss: {training_loss}")

  # Compute the gradients
  training_loss.backward()

  # Take a step to optimize the weights
  optimizer.step()

  #============end of an epoch============

  #End of Training; validation at the end of every epocj

  model.eval() #important to call because we dont want to collect gradients

  with torch.no_grad():
    # Get the model predictions
    input = val_x.to(device)
    y_pred = model(input)

    val_loss = loss(y_pred.squeeze(), val_y)
    print(f"Validation loss: {val_loss}")

    if(val_loss<best_val_loss):
      best_val_loss = val_loss
      print("Saving model checkpoint!")
  print("============")


model.eval()
with torch.no_grad():
  # Get the model predictions
  input = val_x.to(device)
  test_logits = model(input)

y_pred = test_logits.squeeze().round()
print(y_pred)
print(accuracy_score(val_y, y_pred))

```

</details>